### PR TITLE
ldflags as an Option

### PR DESCRIPTION
**Pull request by AngelTomkins**
This is the way that I did it for a "quick fix." I am unsure if the way I did it is the best way. Hopefully this helps :D

### CODE REVIEW

**Comment by AntonioND** [comment]
Actually, this looks like a pretty reasonable patch. The only thing: can you add the option to set `ldflags` in `Arm7Binary.__init__`?

Also, squash your commits and call the resulting commit something like `core: Allow users to set ldflags".

**Comment by AngelTomkins** [comment]
I added the options in Arm7Binary.__init__ and I think I did the git squash. First time doing it so let me know if it should be done differently.

**Comment by AntonioND** [comment]
Actually, can you rebase it? I usually prefer to merge commits without any changes so that they appear with their original author:

```
git fetch --all
git rebase origin/master
git push [myfork] ldflags -f
```

The commit is fine, though, as soon as this is done I'll apply the patch.

**Comment by AntonioND** [comment]
Nevermind, after a quick chat in Discord I've just rebased the branch myself and pushed the changes: https://github.com/AntonioND/architectds/commit/f04dafa739837bd0336bf208a627ca165d1c73bf

**Pull request closed without merging**
